[package]
name = "kaparser"
version = "0.0.1"
edition = "2024"
authors = ["K--Aethiax"]

description = "K--Aethiax's common parser, a procedure oriented parser."

documentation = "https://docs.rs/kaparser"
repository = "https://github.com/eternal-io/kaparser"
license = "MIT OR Apache-2.0"
readme = false

[features]
default = ["std"]
std = ["memchr/std", "simdutf8/std"]

[dependencies]
paste = "1.0.15"
unicode-ident = "1.0.16"
memchr = { version = "2.7.4", default-features = false }
simdutf8 = { version = "0.1.5", default-features = false }
